name: Publish artifacts to Maven Central

on:
  workflow_dispatch:
    inputs:
      version:
        description: Version
        default: 0.3.15

jobs:
  build-native:
    runs-on: ${{ matrix.os }}
    env:
      target-path: ${{ matrix.platform }}-${{ matrix.arch }}
    strategy:
      matrix:
        platform: [linux, win32, darwin]
        arch: [x86, x86-64, aarch64]
        exclude:
          - platform: darwin
            arch: x86
          - platform: win32
            arch: aarch64
          - platform: win32
            arch: x86
        include:
          - platform: darwin
            os: macos-14
            brew-packages: swig
            cmd: ./build.sh
          - platform: darwin
            arch: x86-64
            # https://github.com/openjdk/jdk/commit/5b1baa3d10d9ef3f07f133ece8a5f1d40311c74d#diff-6078ab1e47c6bb312b7f41e7539b4849189260c38f9b359c205a5aa0f633533dR278
            cmd: CC='cc -target x86_64-apple-darwin20.1.0' CXX='c++ -std=c++11 -target x86_64-apple-darwin20.1.0' ./build.sh && mv supranational/blst/Mac/{aarch64,x86_64}
          - platform: linux
            os: ubuntu-22.04
            extra-packages: gcc-9 g++-9
            cmd: CC=gcc-9 CXX=g++-9 ./build.sh
          - platform: linux
            arch: aarch64
            extra-packages: gcc-9-aarch64-linux-gnu g++-9-aarch64-linux-gnu
            cmd: CC=aarch64-linux-gnu-gcc-9 CXX=aarch64-linux-gnu-g++-9 ./build.sh && mv supranational/blst/Linux/{amd64,aarch64}
          - platform: linux
            arch: x86
            extra-packages: gcc-9-multilib g++-9-multilib
            cmd: CC='gcc-9 -m32' CXX='g++-9 -m32' ./build.sh && mv supranational/blst/Linux/{amd64,x86}
          - platform: win32
            os: windows-2022
            cmd: bash -c './build.sh'

    steps:
      - uses: actions/checkout@v4
        with:
          repository: supranational/blst
          ref: v${{ inputs.version }}
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'
      - if: ${{ matrix.extra-packages }}
        run: |
          sudo apt-get update
          sudo apt-get install -y ${{ matrix.extra-packages }}
      - if: ${{ matrix.brew-packages }}
        run: brew install ${{ matrix.brew-packages }}
      - name: Build native image
        run: |
          cd bindings/java
          ${{ matrix.cmd }}
      - uses: actions/upload-artifact@v4
        with:
          name: blst-${{ env.target-path }}.zip
          path: |
            bindings/java/supranational/blst
            !bindings/java/supranational/blst/*.class

  publish:
    runs-on: ubuntu-latest
    needs: build-native
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: 11
          distribution: temurin
          check-latest: true
          cache: maven
          server-id: central
          server-username: OSSRH_USERNAME
          server-password: OSSRH_PASSWORD
          gpg-private-key: ${{ secrets.OSSRH_GPG_KEY }}
      - uses: actions/download-artifact@v4
        with:
          merge-multiple: true
          path: artifacts/
      - env:
          OSSRH_USERNAME:  ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD:  ${{ secrets.OSSRH_PASSWORD }}
          MAVEN_GPG_PASSPHRASE:  ${{ secrets.OSSRH_GPG_PASSPHRASE }}
        run: |
          mkdir -p src/main/{resources,java}/supranational/blst
          mv artifacts/*.java src/main/java/supranational/blst
          mv artifacts/* src/main/resources/supranational/blst/
          mvn versions:set -DnewVersion=${{ inputs.version }}-SNAPSHOT -DgenerateBackupPoms=false
          mvn -B deploy
